.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. 5g_qt test_5g_qt
clean: FORCE
	$(MAKE) -C .. 5g_qt_clean test_5g_qt_clean
check: FORCE
	$(MAKE) -C .. test_5g_qt_check
5g-qt 5g-qt.exe: FORCE
	 $(MAKE) -C .. 5g_qt
